inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/**/*'
    - 'spec/**/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/*'
    - 'bin/*'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false
